version: '3'
services:
  app:
    build: .
    environment:
      AZURE_STORAGE_KEY: ${AZURE_STORAGE_KEY}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
    volumes:
      - ./src:/app

